name: Wine Fedora lsteamclient CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:

      - uses: actions/checkout@v4
      - name: Compilation
        run: |
          sudo dnf -y -q upgrade --refresh
          cd wine-tkg-git
          sed -i 's/pkgname=wine-tkg/pkgname=wine-xiv/' non-makepkg-build.sh
          sed -i 's/_wayland_driver="false"/_wayland_driver="true"/' customization.cfg
          sed -i 's/_NOLIB32="false"/_NOLIB32="wow64"/' wine-tkg-profiles/advanced-customization.cfg
          echo '_ci_build="true"' >> customization.cfg
          echo '_lsteamclient_patches="true"' >> customization.cfg
          for f in wine-tkg-userpatches/*.lsc; do mv "$f" "wine-tkg-userpatches/$(basename ${f%.lsc}).mypatch"; done
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-xiv-lsc-fedora
          path: wine-tkg-git/non-makepkg-builds
